project_id = "gpnpkkraonnotlhuhrme"
[storage.image_transformation]
enabled = false

[auth]
enabled = true
site_url = "https://nextjs-ai-chatbot-three-chi-50.vercel.app"
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1m0s"
otp_length = 6
otp_expiry = 86400
